### PR TITLE
Persist last completed round & restore state from it on start

### PR DESCRIPTION
**Pull request by cap10morgan**
OK, I think we have a working solution here now. Starting over and pairing with @brandonwestcott helped a lot.

[Trello card](https://trello.com/c/G5AcP6dE)

### CODE REVIEW

**Comment by cap10morgan** [comment]
I tested this by having the docker-compose stack use a volume w/ badger storage, started up a network, and then pointed the set-and-get-data WASM example at it. I ran that, shut down the network, then started the network back up. It started at the correct height and seemed to republish the previously completed round.

**Comment by cap10morgan** [comment]
> This looks good. I think there’s some refactor possible but the logic seems sound. As is, it’s only keeping the last completed which I think is a problem in a network shutdown situation where signers are at different heights. There would be no way for them to recover.
> 
> That being said I think this is step one towards that.

Yeah Brandon and I were wondering about that. We thought maybe having _a_ past completed round and all of the global state stuff wired back up would allow it to eventually get back in sync even if it were more than one round behind. But it sounds like that might not be the case. Are you thinking it should reload all completed rounds? And/or are you suggesting there’s more work to do with the current round?

**Comment by cap10morgan** [comment]
Oh, is it that the _other_ nodes won’t still have your last completed round when you all try to come back if you were behind?

**Comment by brandonwestcott** [comment]
I think the case @tobowers is referring to is if the full network shuts down, and nodes A and B are on round 2, but node C is still on round 1. When the network comes back up, node C will try and get votes for round 1, but nodes A & B can't respond [here](https://github.com/quorumcontrol/tupelo/blob/655f637c40fc96d2d3758e6a0e9a527b3a6106ca/gossip/node.go#L499) with round 1 votes because its no longer in round holder

**Pull request merged**
